### ISSUE TITLE
balance.py crashes with ValueError

### ISSUE THREAD

**Issue by djseeds** [opendime/opendime#3]
I received an OpenDime today, and after loading it with some bitcoin I wanted to test out the `balance.py` script, but I am getting this error:
```
Chain.so             X.XXXXXXXX BTC
 Local Bitcoins      X.XXXXXXXX BTC
 Blockr.io           Traceback (most recent call last):
  File "/Volumes/OPENDIME/advanced/balance.py", line 17, in <module>
    import pycode.od_wallet; pycode.od_wallet.main()
  File "/Volumes/OPENDIME/support/pycode.zip/pycode/od_wallet.py", line 145, in main
  File "/Volumes/OPENDIME/support/pycode.zip/pycode/od_wallet.py", line 70, in find_balance
AttributeError: 'exceptions.ValueError' object has no attribute 'code' 
```

It looks like you are expecting a certain type of error (with a `code` attribute) but `ValueError` occurs somewhere instead.

Running with python3 gives more info (but different error):

``` Blockr.io           Traceback (most recent call last):
  File "/Volumes/OPENDIME/support/pycode.zip/pycode/od_wallet.py", line 68, in find_balance
  File "/var/folders/1s/vgx_bydj49df53c2k614bzsr0000gq/T/tmpqcbqmd6h.zip/pycoin/services/blockr_io.py", line 25, in spendables_for_address
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/OPENDIME/advanced/balance.py", line 17, in <module>
    import pycode.od_wallet; pycode.od_wallet.main()
  File "/Volumes/OPENDIME/support/pycode.zip/pycode/od_wallet.py", line 145, in main
  File "/Volumes/OPENDIME/support/pycode.zip/pycode/od_wallet.py", line 70, in find_balance
AttributeError: 'JSONDecodeError' object has no attribute 'code'
```

**Comment by doc-hex** [comment]
I will investigate more, but this sort of error typically happens when a data provider changes the details of their API. 

Thanks for the bug report.

**Comment by djseeds** [comment]
No problem, thanks for a great product!

**Comment by galderz** [comment]
I'm also having this issue, any way to skip providers? I want to move the funds out and seems like this error makes the python script unusable for moving funds out?

**Comment by doc-hex** [comment]
I think it shouldn't be too hard to extract the script and edit it to comment out some of the providers.

The code is in `pycode.zip` IIRC.

**Comment by galderz** [comment]
Did that and was able to comment the problematic line, but was unable to move the funds using the script, I got 2 errors from the providers. Eventually abandoned the script altogether and imported the private key into my node and transferred from there. I was expecting opendime to be more usable for non technical people, but I'm afraid it's not.
