### ISSUE TITLE
trustme.py - IndexError: list index out of range

### ISSUE THREAD

**Issue by neilscudder** [opendime/opendime#7]
I am trying to verify an opendime v4.

OS: Clear Linux
Kernel: 5.1.10-783.native
Python version 3.7.3
pycoin-0.80
libusb-1.0.22b4
PyUSB-1.0.2

All three tests below show the same output. Any help would be appreciated.

Output from the trustme.py on the opendime:
```
Opendime Version: 2.4.0

      time: 20190207.130255
       git: master@e233940e
      coin: BTC
    serial: REDACATED
Downloading ecdsa (wait)...

Additional low-level checks:
  - correct virtual disk geometry
Traceback (most recent call last):
  File "./trustme.py", line 31, in <module>
    import pycode.trust_me; pycode.trust_me.main()
  File "../support/pycode.zip/pycode/trust_me.py", line 260, in main
  File "../support/pycode.zip/pycode/trust_me.py", line 136, in lowlevel_tests
IndexError: list index out of range
```

Output from the trustme.py of a trusted Opendime v3 (run against the new one):
```
Opendime Version: 2.4.0

      time: 20190207.130255
       git: master@e233940e
      coin: BTC
    serial: REDACTED
Downloading ecdsa (wait)...

Additional low-level checks:
  - correct virtual disk geometry
Traceback (most recent call last):
  File "./trustme.py", line 31, in <module>
    import pycode.trust_me; pycode.trust_me.main()
  File "../support/pycode.zip/pycode/trust_me.py", line 260, in main
  File "../support/pycode.zip/pycode/trust_me.py", line 136, in lowlevel_tests
IndexError: list index out of range
```
Output from the trustme.py in the github repo (v2.4, new):
```
Opendime Version: 2.4.0

      time: 20190207.130255
       git: master@e233940e
      coin: BTC
    serial: REDACTED
Downloading ecdsa (wait)...

Additional low-level checks:
  - correct virtual disk geometry
Traceback (most recent call last):
  File "./trustme.py", line 31, in <module>
    import pycode.trust_me; pycode.trust_me.main()
  File "../support/pycode.zip/pycode/trust_me.py", line 260, in main
  File "../support/pycode.zip/pycode/trust_me.py", line 136, in lowlevel_tests
IndexError: list index out of range
```

**Comment by doc-hex** [comment]
The error points to parsing issue with the output from `openssl`. It runs a command like this:

```
openssl x509 -in .../advanced/unit.crt -noout -subject
```

and expects to be able to split the output (single line) on `/`.

Can you run that command and see what the output is? Thanks!

**Comment by neilscudder** [comment]
Output is 
```
subject=serialNumber = "JETJEECBIZIFCIBAEBGDGBIU74+de5cc35e8548", CN = Opendime
```
with a newline at the end

**Comment by doc-hex** [comment]
Looks like a compatibility issue with the OpenSSL binary you have. On my system (Mac OS):

```
% openssl version
LibreSSL 2.6.5
% openssl x509 -in /Volumes/OPENDIME/advanced/unit.crt -noout -subject
subject= /serialNumber=QJJDCQKSLFFVASRRFYYAOEQE74+88b21c2ec4c2/CN=Opendime
```

In a future version, we can generalize the code in `trustme.py` to handle these differences but that will not help you today.

Options:
- take apart the code in trustme.py, and edit to match your system's output (start by unziping `support/pycode.zip`)
- use other code to verify device, such as our [Chrome extension](https://github.com/opendime/chrome-opendime-extension) or [M5 Stack verifier](https://github.com/opendime/m5verifier)
- use some other computer with different OpenSSL version (easiest option)

**Comment by neilscudder** [comment]
Thanks for your help. I'm going to try and patch the script.

**Comment by neilscudder** [comment]
Here is what I got working (diff of trustme.py):
```
135,141c135,138
<     x = subprocess.check_output(['openssl', 'x509', '-in', unit, '-noout', '-subject', '-nameopt', 'sep_comma_plus_space', '-nameopt', 'dn_rev'  ])
<     subj = B2A(x).split(',')[1]
<     sn_offered = subj.split('=')[1]
<     sn_expected = expect['sn'] + "+" + expect['ae']
<     if sn_offered.rstrip() != sn_expected:
<         fail("Certificate is for some other unit: " + sn_offered.rstrip())
---
>     x = subprocess.check_output(['openssl', 'x509', '-in', unit, '-noout', '-subject' ])
>     subj = B2A(x).split('/')[1]
>     if subj != 'serialNumber=' + expect['sn'] + '+' + expect['ae']:
>         fail("Certificate is for some other unit: " + subj)
```

Could you please test if you get the same output as below with libressl?
```
% openssl x509 -in ../advanced/unit.crt -noout -subject -nameopt sep_comma_plus_space,dn_rev 
subject=CN=Opendime, serialNumber=JETJEECBIZIFCIBAEBGDGBIU74+de5cc35e8548
```

**Comment by ln2max** [comment]
See the above-linked PR for a fix to the same issue on a different OpenSSL version. It is not a complete fix, but it includes enough debugging statements (`<insert crying code reviewer>`) to cobble together fixes on other systems if need be!
